// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:451b0613-b09f-4e98-98f2-4c4e867273ad",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_J9POde62i",
    "aws_user_pools_web_client_id": "1ot5nn8nd6arkvlhofp953rmg6"
};


export default awsmobile;
